[theme]
primaryColor = "#2563eb"
backgroundColor = "#09090b"
secondaryBackgroundColor = "#0c0c0f"
textColor = "#fafafa"
font = "sans serif"

[server]
headless = true
port = 8501

[browser]
gatherUsageStats = false
